if(NOT DEFINED FFMPEG_BUILD_DIR OR NOT DEFINED FFMPEG_PREFIX)
  message(FATAL_ERROR "FFMPEG_BUILD_DIR and FFMPEG_PREFIX are required")
endif()

set(_config "${FFMPEG_BUILD_DIR}/config.h")
set(_components "${FFMPEG_BUILD_DIR}/config_components.h")

function(require_define file_path name value)
  file(STRINGS "${file_path}" matches REGEX "^#define ${name} ${value}$")
  list(LENGTH matches count)
  if(NOT count EQUAL 1)
    message(FATAL_ERROR "Expected exactly '#define ${name} ${value}' in ${file_path}")
  endif()
endfunction()

function(require_components kind)
  set(expected ${ARGN})
  file(STRINGS "${_components}" lines REGEX "^#define CONFIG_.*_${kind} 1$")
  set(actual)
  foreach(line IN LISTS lines)
    string(REGEX REPLACE "^#define CONFIG_(.*)_${kind} 1$" "\\1" component "${line}")
    list(APPEND actual "${component}")
  endforeach()
  list(SORT actual)
  list(SORT expected)
  if(NOT "${actual}" STREQUAL "${expected}")
    message(FATAL_ERROR
      "Unexpected ${kind} allowlist. Expected '${expected}', found '${actual}'")
  endif()
endfunction()

require_define("${_config}" CONFIG_GPL 0)
require_define("${_config}" CONFIG_NONFREE 0)
require_define("${_config}" CONFIG_VERSION3 0)
require_define("${_config}" CONFIG_NETWORK 0)
require_define("${_config}" CONFIG_ICONV 0)
require_define("${_config}" CONFIG_SHARED 1)
require_define("${_config}" CONFIG_STATIC 0)
require_define("${_config}" CONFIG_FFMPEG 0)
require_define("${_config}" CONFIG_FFPLAY 0)
require_define("${_config}" CONFIG_FFPROBE 0)

require_components(DECODER
  ATRAC3P FLAC MP3 MP3FLOAT OPUS PCM_F32LE PCM_S16LE PCM_S24LE PCM_S32LE PCM_U8 VORBIS)
require_components(DEMUXER FLAC MP3 OGG WAV)
require_components(PARSER FLAC MPEGAUDIO OPUS VORBIS)
require_components(PROTOCOL FILE)
require_components(ENCODER)
require_components(MUXER)
require_components(FILTER)

foreach(license_file COPYING.LGPLv2.1 LICENSE.md configure-options.txt)
  if(NOT EXISTS "${FFMPEG_PREFIX}/licenses/FFmpeg/${license_file}")
    message(FATAL_ERROR "Missing installed FFmpeg compliance file: ${license_file}")
  endif()
endforeach()

file(READ "${FFMPEG_PREFIX}/licenses/FFmpeg/configure-options.txt" configure_manifest)
string(FIND "${configure_manifest}" "--prefix=<INSTALL_PREFIX>" placeholder_position)
if(placeholder_position EQUAL -1)
  message(FATAL_ERROR "FFmpeg configure manifest does not use the portable install-prefix placeholder")
endif()
if(DEFINED FFMPEG_FORBIDDEN_PATH)
  string(FIND "${configure_manifest}" "${FFMPEG_FORBIDDEN_PATH}" private_path_position)
  if(NOT private_path_position EQUAL -1)
    message(FATAL_ERROR "FFmpeg configure manifest contains the local source path")
  endif()
endif()

foreach(library avutil avcodec avformat swresample)
  if(FFMPEG_WINDOWS)
    file(GLOB matches "${FFMPEG_PREFIX}/bin/*${library}*.dll")
  else()
    file(GLOB matches "${FFMPEG_PREFIX}/lib/lib${library}.so*")
  endif()
  if(NOT matches)
    message(FATAL_ERROR "Missing shared FFmpeg library: ${library}")
  endif()
endforeach()

message(STATUS "FFmpeg configuration and installed files match the reviewed allowlist")
