#!/usr/bin/env sh
set -eu

slang_version=2026.18
slang_sha256=e45ea4f117d51b8c1e84fa49f562081e73a9f29d02bd4f7fad20678603282829
repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
archive="$repo_root/out/downloads/slang-$slang_version-linux-x86_64-glibc-2.27.tar.gz"
tool_root="$repo_root/out/tools/slang-$slang_version-linux-x86_64"
shader_root="$repo_root/src/Waddamburo.Platform.Sdl/Shaders"
output_root="$shader_root/Compiled"

mkdir -p "$(dirname -- "$archive")" "$repo_root/out/tools" "$output_root"
if [ ! -f "$archive" ]; then
    curl --fail --location --show-error \
        "https://github.com/shader-slang/slang/releases/download/v$slang_version/slang-$slang_version-linux-x86_64-glibc-2.27.tar.gz" \
        --output "$archive"
fi
printf '%s  %s\n' "$slang_sha256" "$archive" | sha256sum --check --status

if [ ! -x "$tool_root/bin/slangc" ]; then
    mkdir -p "$tool_root"
    tar -xzf "$archive" -C "$tool_root"
fi

slangc="$tool_root/bin/slangc"
"$slangc" "$shader_root/quad.vert.glsl" -entry main -stage vertex -target spirv -profile glsl_450 -warnings-as-errors all -o "$output_root/quad.vert.spv"
"$slangc" "$shader_root/quad.frag.glsl" -entry main -stage fragment -target spirv -profile glsl_450 -warnings-as-errors all -o "$output_root/quad.frag.spv"
for shader in don.vert don.frag don-post.vert don-post.frag; do
    stage=fragment
    case "$shader" in *.vert) stage=vertex ;; esac
    "$slangc" "$shader_root/$shader.glsl" -entry main -stage "$stage" -target spirv -profile glsl_450 -warnings-as-errors all -o "$output_root/$shader.spv"
done
printf 'Built SPIR-V shaders with Slang %s. DXIL is generated by build-shaders.ps1 on Windows.\n' "$slang_version"
