#!/usr/bin/env sh
# Compiles the bgfx .sc shaders for every backend buildable on Linux (Vulkan SPIR-V, GLSL 330,
# ESSL 300, Metal) with the pinned shaderc from the native bgfx build. D3D11 bytecode needs
# Microsoft's compiler and is generated by build-shaders.ps1 on Windows.
set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
bgfx_prefix="${1:-$repo_root/out/build/native/linux-x64/linux-debug/bgfx/prefix}"
shaderc="$bgfx_prefix/bin/shaderc"
shader_root="$repo_root/src/Waddamburo.Platform.Sdl/Shaders/Bgfx"
output_root="$repo_root/src/Waddamburo.Platform.Sdl/Shaders/Compiled"

if [ ! -x "$shaderc" ]; then
    echo "shaderc not found at $shaderc; build native with -DWADDAMBURO_BUILD_BGFX=ON first." >&2
    exit 1
fi
mkdir -p "$output_root"

# name varying-def
for entry in vs_quad:quad fs_quad:quad fs_mask:quad vs_don:don fs_don:don vs_don_post:post fs_don_post:post; do
    name=${entry%%:*}
    varying="$shader_root/${entry#*:}.varying.def.sc"
    type=fragment
    case "$name" in vs_*) type=vertex ;; esac
    # token:profile:platform
    for target in spirv:spirv:linux glsl:330:linux essl:300_es:android metal:metal:osx; do
        token=${target%%:*}
        rest=${target#*:}
        "$shaderc" -f "$shader_root/$name.sc" -o "$output_root/$name.$token.bin" \
            --type "$type" --varyingdef "$varying" -i "$bgfx_prefix/include/bgfx" \
            --platform "${rest#*:}" -p "${rest%%:*}"
    done
done
printf 'Built bgfx shaders (spirv, glsl, essl, metal). D3D11 is generated by build-shaders.ps1 on Windows.\n'
