<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ppy.SDL3-CS" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Waddamburo.Formats/Waddamburo.Formats.csproj" />
    <ProjectReference Include="../Waddamburo.Lumen/Waddamburo.Lumen.csproj" />
  </ItemGroup>

</Project>
